<?php

class A{
    private $a = 1;
    public function dog(){

        var_dump($this->a);
        $this->cat();
        $this->monkey();
        static::cat();
        static::monkey();
        //static::dog();
    }
    private function cat(){

       var_dump(__LINE__);
    }
    protected  function monkey(){

        var_dump(__LINE__);
    }
}

class B extends A{
    private $a = 2;

    public function cat(){

        var_dump(__LINE__);
    }

    protected function monkey()
    {
    //    parent::monkey(); // TODO: Change the autogenerated stub
        var_dump(__LINE__);
    }
}

$obj = new A();
$obj->dog();
$obj = new B();
$obj->dog();

/*class BBB extends CCC{

}*/
//var_dump(new CCC);
class CCC extends  PP{

}
var_dump(new CCC());

var_dump(new PP());

class PP{

static  $a = 2;
static $cc = 2+2;
//public $a = 33;
}
$obj = new PP();
echo $obj::$cc;
//$obj->cc;




